connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: xiangxinsun
  password: root

development:
  <<: *connection
  database: dbname_development

test:
  <<: *connection
  database: dbname_test

production:
  <<: *connection
  database: dbname_production